name: Test, Build & Deploy Starrocks UDF

on:
  push:
    tags:
      - 'v*'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Extract version from tag
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Set Maven project version
        run: mvn versions:set -DnewVersion=${{ steps.extract_version.outputs.VERSION }}

      - name: Run tests
        run: mvn test

      - name: Build fat JAR
        run: mvn package -DskipTests

      - name: Deploy to GitHub Packages
        run: mvn deploy -DskipTests --batch-mode
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JAR to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/*-jar-with-dependencies.jar
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}